name: anitex
description: Anitex is a implicitly animated text widget, which animates on passed text changes
version: 3.0.0
repository: https://github.com/alphamikle/anitex
homepage: https://github.com/alphamikle/anitex

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: